### ISSUE TITLE
11/9/2022 10:55AM - Issue Clarification & Next Steps

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Midterm-Group-Project#21]
**GOAL: Midterm individual critique review** 

**Attendance:** 
- [x] Amber Garcia
- [x] Adrian Noa
- [x] Jasminder Garcha
- [x] Wade Li
- [ ] Oliver Vidal (Family emergency)

**To-Do**
- [ ] Review the SubDomain Issues created & clarify
- [ ] Next Steps for proper submission

**Notes**
- [ ]

**Comment by jaga41** [comment]
In my second revision of the individual midterm, I added Subject Areas (History, Human Resources, Production, Sales, Views) and color coded each table in them using the Peter Coad archetypes. Maybe we can use some of that!
