### ISSUE TITLE
11/4/2022 5:30PM Midterm Individual Critiques

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Midterm-Group-Project#4]
**GOAL: Midterm individual critique review** 

**Attendance:** 
- [x] Amber Garcia
- [x] Adrian Noa
- [x] Jasminder Garcha
- [x] Wade Li
- [ ] Oliver Vidal (Family emergency)

**To-Do**
- [ ] Review critiques

**Notes**
- [ ] Create (5-15) templates for default values and check constraints
- [ ] 50-60 UDTs (more domains than DF and CK)
- [ ] d > sd > udt camelcasing
- [ ] Definition to define UDT
- [ ] Comment to give creator credit of UDT
